export const actions = {
  SET_SELECTED: "SET_SELECTED",
  CLEAR_SELECTED: "CLEAR_SELECTED",
  SET_SHOW_FILTERS: "SET_SHOW_FILTERS",
  SET_SEARCH_FOR: "SET_SEARCH_FOR",
  SET_SORT_BY: "SET_SORT_BY",
};
